baseURL = "https://hindutva.github.io/"
languageCode = "en-us"
title = "hindu-vichArAH हिन्दु-विचाराः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/hindutva/hindutva.github.io/edit/hugo-source/content/"
  contactLink = "https://github.com/hindutva/hindutva.github.io/issues/new"
  build_img = "https://github.com/hindutva/hindutva.github.io/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/hindutva/hindutva.github.io/actions/workflows/build.yml"
  env = "production"
  # disqusShortcode = "hindutva"
  background_color_class = "bg-light-red"
  body_classes = "bg-washed-yellow"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
   unsafe = true


[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2
